---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-backend
  template:
    metadata:
      labels:
        app: vote-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: vote-backend
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: vote-backend
spec:
  ports:
  - port: 6379
  selector:
    app: vote-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: vote-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: vote-frontend
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "vote-backend"
---
apiVersion: v1
kind: Service
metadata:
  name: vote-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: vote-frontend